# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  analyze-tags:
    runs-on: ubuntu-latest
    outputs:
      latest-tag: ${{ steps.latesttag.outputs.tag }}
    steps:
      - name: Clone Git repository
        uses: actions/checkout@v2
        with:
          repository: meisnate12/Plex-Meta-Manager
          fetch-depth: 0

      - name: Get latest tag
        id: latesttag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - name: Echo var
        id: var
        shell: bash
        run: echo "$GITHUB_CONTEXT"
